export const characters = [
  {
    id: 1,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    name: 'Rick Sanchez',
    status: 'alive',
    gender: 'Female',
  },
  {
    id: 2,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    name: 'Morty Smith',
    status: 'alive',
    gender: 'Male',
  },
  {
    id: 3,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    name: 'Summer Smith',
    status: 'dead',
    gender: 'Female',
  },
  {
    id: 4,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    name: 'Beth Smith',
    alive: 'dead',
    gender: 'Male',
  },
  {
    id: 5,
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    name: 'Jerry Smith',
    status: 'alive',
    gender: 'Male',
  },
  {
    id: 6,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    name: 'Personaje 5',
    status: 'alive',
    gender: 'Female',
  },
  {
    id: 7,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    name: 'Personaje 6',
    status: 'alive',
    gender: 'Male',
  },
  {
    id: 8,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    name: 'Personaje 7',
    status: 'dead',
    gender: 'Female',
  },
  {
    id: 9,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    name: 'Personaje 8',
    alive: 'dead',
    gender: 'Male',
  },
  {
    id: 10,
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    name: 'Personaje 9',
    status: 'alive',
    gender: 'Male',
  },
];
